version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    volumes:
      - /home/mapat221/ci/devops_labs/docker-lab5/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456